version: "3"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      SA_PASSWORD: "Pa55w0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    expose:
      - "1433"
    volumes:
      - mssql_volume:/var/lib/mysql
volumes:
  mssql_volume:

